# Programación Dinámica

Notebook para probar cómo pasar un algoritmo recursivo a un algoritmo iterativo obteniendo el mismo resultado con mejor complejidad Big-O

In [1]:
from tp2.archivos import leer_archivo

datos = leer_archivo("../examples/10.txt")
datos

([36, 2, 78, 19, 59, 76, 65, 64, 33, 41],
 [63, 61, 49, 41, 40, 38, 23, 17, 13, 10])

In [16]:
def _ganancia_del_dia(dia_entrenamiento, dia_desde_descanso, ganancia_por_dia, energia_por_dia):
    if dia_entrenamiento == len(ganancia_por_dia):
        return 0

    ganancia = ganancia_por_dia[dia_entrenamiento]
    energia = energia_por_dia[dia_desde_descanso]
    return min(ganancia, energia)
    
def mejor_ganancia_recursivo_con_memoria(ganancia_por_dia, energia_por_dia, dia_a_analizar, dias_desde_descanso, M):
    if dia_a_analizar == len(ganancia_por_dia):
        return 0
    
    ganancia_guardada = M[dia_a_analizar][dias_desde_descanso]

    if ganancia_guardada != None:
        return ganancia_guardada

    ganancia_entrenando_hoy = (_ganancia_del_dia(dia_a_analizar, dias_desde_descanso, ganancia_por_dia, energia_por_dia) 
                        + mejor_ganancia_recursivo_con_memoria(ganancia_por_dia, energia_por_dia, dia_a_analizar + 1, dias_desde_descanso + 1, M))
    ganancia_descansando_hoy = mejor_ganancia_recursivo_con_memoria(ganancia_por_dia, energia_por_dia, dia_a_analizar + 1, 0, M)

    ganancia_guardada = max(ganancia_entrenando_hoy, ganancia_descansando_hoy)

    M[dia_a_analizar][dias_desde_descanso] = ganancia_guardada
    
    return ganancia_guardada

M = [[None for _ in datos[0]] for _ in datos[0]]
mejor_ganancia_recursivo_con_memoria(datos[0], datos[1], 0, 0, M)

380

In [3]:
import pandas as pd
pd.DataFrame(M)

     0      1      2      3      4      5      6     7     8     9
0  380    NaN    NaN    NaN    NaN    NaN    NaN   NaN   NaN   NaN
1  344  344.0    NaN    NaN    NaN    NaN    NaN   NaN   NaN   NaN
2  344  342.0  330.0    NaN    NaN    NaN    NaN   NaN   NaN   NaN
3  281  281.0  281.0  281.0    NaN    NaN    NaN   NaN   NaN   NaN
4  281  257.0  247.0  246.0  246.0    NaN    NaN   NaN   NaN   NaN
5  246  222.0  198.0  198.0  198.0  198.0    NaN   NaN   NaN   NaN
6  198  183.0  161.0  137.0  137.0  137.0  137.0   NaN   NaN   NaN
7  137  135.0  122.0  112.0   96.0   79.0   74.0  74.0   NaN   NaN
8   74   74.0   74.0   73.0   71.0   56.0   41.0  41.0  41.0   NaN
9   41   41.0   41.0   41.0   40.0   38.0   23.0  17.0  13.0  10.0

In [4]:
def mejor_ganancia_iterativo(ganancia_por_dia, energia_por_dia):
    cant_dias = len(ganancia_por_dia)

    M = [[0 for _ in range(cant_dias+1)] for _ in range(cant_dias+1)]
    
    for dia_a_analizar in range(cant_dias):
        for dias_desde_descanso in range(dia_a_analizar + 1):
            M[dia_a_analizar][dias_desde_descanso] = _ganancia_del_dia(dia_a_analizar, dias_desde_descanso, ganancia_por_dia, energia_por_dia)
    
    for dia_a_analizar in range(cant_dias-1, -1, -1):
        for dias_desde_descanso in range(dia_a_analizar + 1):
            ganancia_si_descanso = M[dia_a_analizar+1][0]
            ganancia_si_entreno = M[dia_a_analizar][dias_desde_descanso] + M[dia_a_analizar+1][dias_desde_descanso+1]
            M[dia_a_analizar][dias_desde_descanso] = max(ganancia_si_descanso, ganancia_si_entreno)
            
    return M

G = mejor_ganancia_iterativo(*datos)
pd.DataFrame(G)

     0    1    2    3    4    5    6   7   8   9   10
0   380    0    0    0    0    0    0   0   0   0   0
1   344  344    0    0    0    0    0   0   0   0   0
2   344  342  330    0    0    0    0   0   0   0   0
3   281  281  281  281    0    0    0   0   0   0   0
4   281  257  247  246  246    0    0   0   0   0   0
5   246  222  198  198  198  198    0   0   0   0   0
6   198  183  161  137  137  137  137   0   0   0   0
7   137  135  122  112   96   79   74  74   0   0   0
8    74   74   74   73   71   56   41  41  41   0   0
9    41   41   41   41   40   38   23  17  13  10   0
10    0    0    0    0    0    0    0   0   0   0   0